-- ═══════════════════════════════════════════════════════════════════
-- Buyer Reference System — Phase 1
--
-- Creates the full attribution protection infrastructure:
--
--   1. buyer_enquiries       — backfill schema (live table, not in migrations yet)
--   2. buyers                — verified buyer profiles with AV-YEAR-CC-NNNNN refs
--   3. partner_users         — partner portal auth mapping (used in Phase 3)
--   4. technology_fees       — fee ledger (used in Phase 3)
--   5. generate_buyer_ref()  — sequence-safe reference generator
--   6. check_buyer_attribution() — attribution lookup by email/phone
--   7. Trigger               — auto-populates buyer_ref on INSERT into buyers
--   8. RLS policies          — buyers see own record; partners see own pipeline
--
-- All CREATE statements are IF NOT EXISTS / OR REPLACE so this migration
-- is safe to re-run against a live database.
-- ═══════════════════════════════════════════════════════════════════


-- ── 1. buyer_enquiries (backfill only — table already exists live) ──
CREATE TABLE IF NOT EXISTS public.buyer_enquiries (
  id             bigserial PRIMARY KEY,
  listing_id     bigint REFERENCES public.listings(id) ON DELETE SET NULL,
  buyer_name     text NOT NULL,
  buyer_email    text NOT NULL,
  buyer_phone    text,
  buyer_location text,
  message        text,
  journey_stage  text DEFAULT 'enquiry' CHECK (journey_stage IN ('enquiry','concierge','contact','waitlist')),
  status         text DEFAULT 'new' CHECK (status IN ('new','responded','in_progress','completed')),
  responded_at   timestamptz,
  created_at     timestamptz DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_buyer_enquiries_email ON public.buyer_enquiries (buyer_email);
CREATE INDEX IF NOT EXISTS idx_buyer_enquiries_listing_id ON public.buyer_enquiries (listing_id);


-- ── 2. buyers — verified buyer profiles ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.buyers (
  id                           uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Core identity
  buyer_name                   text NOT NULL,
  buyer_email                  text NOT NULL,
  buyer_phone                  text,
  country_code                 text NOT NULL DEFAULT 'UK' CHECK (char_length(country_code) BETWEEN 2 AND 3),
  auth_user_id                 uuid REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Reference ID (auto-generated by trigger)
  buyer_ref                    text UNIQUE,
  buyer_ref_generated_at       timestamptz,

  -- Verification level
  verification_level           text DEFAULT 'pending' CHECK (verification_level IN ('pending','kyc_submitted','identity_verified','financially_screened')),

  -- Listing & partner attribution
  listing_id                   bigint REFERENCES public.listings(id) ON DELETE SET NULL,
  introduced_to_partner_id     uuid REFERENCES public.saccos(id) ON DELETE SET NULL,
  introduced_at                timestamptz,
  attribution_window_expires_at timestamptz,

  -- Introduction pipeline
  introduction_status          text DEFAULT 'pending' CHECK (introduction_status IN ('pending','introduced','consulting','deposited','completed','withdrawn')),

  -- Transaction outcome
  transaction_completed_at     timestamptz,
  land_value_kes               numeric(14,2),

  -- Technology services fee (2.5% of land value)
  technology_fee_amount        numeric(14,2),
  technology_fee_status        text DEFAULT 'pending' CHECK (technology_fee_status IN ('pending','invoiced','paid','waived')),

  created_at                   timestamptz DEFAULT NOW(),
  updated_at                   timestamptz DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_buyers_email ON public.buyers (buyer_email);
CREATE INDEX IF NOT EXISTS idx_buyers_phone ON public.buyers (buyer_phone);
CREATE INDEX IF NOT EXISTS idx_buyers_buyer_ref ON public.buyers (buyer_ref);
CREATE INDEX IF NOT EXISTS idx_buyers_partner_id ON public.buyers (introduced_to_partner_id);
CREATE INDEX IF NOT EXISTS idx_buyers_listing_id ON public.buyers (listing_id);
CREATE INDEX IF NOT EXISTS idx_buyers_auth_user_id ON public.buyers (auth_user_id);
CREATE INDEX IF NOT EXISTS idx_buyers_attribution_window ON public.buyers (attribution_window_expires_at);


-- ── 3. partner_users — portal auth (used in Phase 3) ────────────────
CREATE TABLE IF NOT EXISTS public.partner_users (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  partner_id   uuid NOT NULL REFERENCES public.saccos(id) ON DELETE CASCADE,
  auth_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  email        text NOT NULL,
  role         text NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin','viewer')),
  created_at   timestamptz DEFAULT NOW(),
  UNIQUE (partner_id, email)
);

CREATE INDEX IF NOT EXISTS idx_partner_users_partner_id ON public.partner_users (partner_id);
CREATE INDEX IF NOT EXISTS idx_partner_users_email ON public.partner_users (email);
CREATE INDEX IF NOT EXISTS idx_partner_users_auth_user_id ON public.partner_users (auth_user_id);


-- ── 4. technology_fees — fee ledger (used in Phase 3) ───────────────
CREATE TABLE IF NOT EXISTS public.technology_fees (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  buyer_id           uuid NOT NULL REFERENCES public.buyers(id) ON DELETE CASCADE,
  buyer_ref          text NOT NULL,
  partner_id         uuid NOT NULL REFERENCES public.saccos(id) ON DELETE RESTRICT,
  listing_id         bigint REFERENCES public.listings(id) ON DELETE SET NULL,

  land_value_kes     numeric(14,2) NOT NULL CHECK (land_value_kes >= 0),
  fee_rate           numeric(5,4)  NOT NULL DEFAULT 0.025,
  fee_amount_kes     numeric(14,2) NOT NULL CHECK (fee_amount_kes >= 0),

  status             text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','invoiced','paid','waived')),
  invoiced_at        timestamptz,
  paid_at            timestamptz,
  notes              text,

  transaction_date   date,
  reported_by_email  text,

  created_at         timestamptz DEFAULT NOW(),
  updated_at         timestamptz DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_technology_fees_buyer_id ON public.technology_fees (buyer_id);
CREATE INDEX IF NOT EXISTS idx_technology_fees_partner_id ON public.technology_fees (partner_id);
CREATE INDEX IF NOT EXISTS idx_technology_fees_status ON public.technology_fees (status);


-- ═══════════════════════════════════════════════════════════════════
-- 5. generate_buyer_ref(country_code) — atomic sequence generator
-- ═══════════════════════════════════════════════════════════════════
--
-- Format: AV-YYYY-CC-NNNNN  (e.g. AV-2026-UK-00001)
--
-- Safe under concurrency: uses a transactional scan of existing refs
-- for the (year, country_code) pair to determine the next sequence
-- number. Wrapped in SECURITY DEFINER so it can read the full table
-- even when called from an RLS-restricted client.
-- ═══════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.generate_buyer_ref(p_country_code TEXT DEFAULT 'UK')
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_year        int := EXTRACT(YEAR FROM NOW())::int;
  v_cc          text := UPPER(COALESCE(NULLIF(TRIM(p_country_code), ''), 'UK'));
  v_next_seq    int;
  v_prefix      text;
BEGIN
  -- Normalize GB → UK (Britain uses GB as ISO, but UK in common use)
  IF v_cc = 'GB' THEN
    v_cc := 'UK';
  END IF;

  v_prefix := format('AV-%s-%s-', v_year, v_cc);

  SELECT COALESCE(
    MAX(
      CAST(
        SUBSTRING(buyer_ref FROM length(v_prefix) + 1) AS int
      )
    ),
    0
  ) + 1
  INTO v_next_seq
  FROM public.buyers
  WHERE buyer_ref LIKE v_prefix || '%'
    AND buyer_ref ~ ('^' || v_prefix || '[0-9]+$');

  RETURN v_prefix || LPAD(v_next_seq::text, 5, '0');
END;
$$;

GRANT EXECUTE ON FUNCTION public.generate_buyer_ref(TEXT) TO anon, authenticated, service_role;


-- ═══════════════════════════════════════════════════════════════════
-- 6. check_buyer_attribution(email, phone) — attribution lookup
-- ═══════════════════════════════════════════════════════════════════
--
-- Called by the partner portal when a partner reports a transaction.
-- Returns any buyer in the 24-month attribution window matching
-- either email OR phone. Case-insensitive email match. Phone match
-- is exact — format normalization is the caller's responsibility.
-- ═══════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.check_buyer_attribution(
  p_email TEXT DEFAULT NULL,
  p_phone TEXT DEFAULT NULL
)
RETURNS TABLE (
  buyer_id                      uuid,
  buyer_ref                     text,
  introduced_to_partner_id      uuid,
  introduced_at                 timestamptz,
  attribution_window_expires_at timestamptz,
  introduction_status           text,
  in_window                     boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_email IS NULL AND p_phone IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT
    b.id                                          AS buyer_id,
    b.buyer_ref                                   AS buyer_ref,
    b.introduced_to_partner_id                    AS introduced_to_partner_id,
    b.introduced_at                               AS introduced_at,
    b.attribution_window_expires_at               AS attribution_window_expires_at,
    b.introduction_status                         AS introduction_status,
    (b.attribution_window_expires_at IS NULL
     OR b.attribution_window_expires_at > NOW())  AS in_window
  FROM public.buyers b
  WHERE (p_email IS NOT NULL AND LOWER(b.buyer_email) = LOWER(p_email))
     OR (p_phone IS NOT NULL AND b.buyer_phone = p_phone)
  ORDER BY b.created_at DESC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.check_buyer_attribution(TEXT, TEXT) TO authenticated, service_role;


-- ═══════════════════════════════════════════════════════════════════
-- 7. Trigger — auto-populate buyer_ref on buyer INSERT
-- ═══════════════════════════════════════════════════════════════════
--
-- Every new row in public.buyers immediately gets a buyer_ref and
-- buyer_ref_generated_at timestamp. The reference is permanent from
-- the moment the buyer enters the pipeline.
--
-- Attribution window is also populated here if the caller set
-- introduction_status='introduced' or later (otherwise left NULL
-- until the partner introduction is actually made).
-- ═══════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.buyers_before_insert_populate_ref()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.buyer_ref IS NULL THEN
    NEW.buyer_ref := public.generate_buyer_ref(NEW.country_code);
    NEW.buyer_ref_generated_at := NOW();
  END IF;

  IF NEW.introduction_status IS NOT NULL
     AND NEW.introduction_status <> 'pending'
     AND NEW.introduced_at IS NULL THEN
    NEW.introduced_at := NOW();
    NEW.attribution_window_expires_at := NOW() + INTERVAL '24 months';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS buyers_populate_ref_trigger ON public.buyers;
CREATE TRIGGER buyers_populate_ref_trigger
  BEFORE INSERT ON public.buyers
  FOR EACH ROW
  EXECUTE FUNCTION public.buyers_before_insert_populate_ref();


-- Update trigger — keep updated_at fresh + set introduced_at when status changes
CREATE OR REPLACE FUNCTION public.buyers_before_update_maintain()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();

  -- If status moves from pending → introduced (or later), stamp introduced_at
  IF OLD.introduction_status = 'pending'
     AND NEW.introduction_status <> 'pending'
     AND NEW.introduced_at IS NULL THEN
    NEW.introduced_at := NOW();
    NEW.attribution_window_expires_at := NOW() + INTERVAL '24 months';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS buyers_maintain_trigger ON public.buyers;
CREATE TRIGGER buyers_maintain_trigger
  BEFORE UPDATE ON public.buyers
  FOR EACH ROW
  EXECUTE FUNCTION public.buyers_before_update_maintain();


-- ═══════════════════════════════════════════════════════════════════
-- 8. RLS — partners see only their pipeline; buyers see only their row
-- ═══════════════════════════════════════════════════════════════════

ALTER TABLE public.buyers          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partner_users   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.technology_fees ENABLE ROW LEVEL SECURITY;

-- Buyers: a buyer can read their own row via auth_user_id match
DROP POLICY IF EXISTS buyers_self_read ON public.buyers;
CREATE POLICY buyers_self_read ON public.buyers
  FOR SELECT
  TO authenticated
  USING (auth_user_id = auth.uid());

-- Buyers: partners can read only buyers introduced to their partner_id
-- (resolves the partner_id via a JOIN to partner_users)
DROP POLICY IF EXISTS buyers_partner_read ON public.buyers;
CREATE POLICY buyers_partner_read ON public.buyers
  FOR SELECT
  TO authenticated
  USING (
    introduced_to_partner_id IN (
      SELECT partner_id FROM public.partner_users
      WHERE auth_user_id = auth.uid()
    )
  );

-- Partner users: a partner user can read their own row
DROP POLICY IF EXISTS partner_users_self_read ON public.partner_users;
CREATE POLICY partner_users_self_read ON public.partner_users
  FOR SELECT
  TO authenticated
  USING (auth_user_id = auth.uid());

-- Technology fees: partners see only their own fee ledger
DROP POLICY IF EXISTS technology_fees_partner_read ON public.technology_fees;
CREATE POLICY technology_fees_partner_read ON public.technology_fees
  FOR SELECT
  TO authenticated
  USING (
    partner_id IN (
      SELECT partner_id FROM public.partner_users
      WHERE auth_user_id = auth.uid()
    )
  );

-- Service role bypasses RLS, so admin and server-side writes work normally.

-- ═══════════════════════════════════════════════════════════════════
-- Verify with:
--   SELECT generate_buyer_ref('UK');
--   SELECT * FROM check_buyer_attribution('test@example.com', NULL);
--   INSERT INTO buyers (buyer_name, buyer_email, country_code)
--     VALUES ('Test Buyer', 'test@example.com', 'UK');
--   SELECT buyer_ref FROM buyers WHERE buyer_email='test@example.com';
-- ═══════════════════════════════════════════════════════════════════
